import type {
  ActivityItem,
  AlertItem,
  ApiEndpoint,
  DashboardMetrics,
  Environment,
  Project,
  Release,
  TeamMember,
} from './types'

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'Portal de Pagamentos',
    description: 'Plataforma de checkout e processamento de pagamentos com suporte a múltiplos gateways e antifraude.',
    framework: 'Laravel',
    language: 'PHP',
    repository: 'github.com/acme/payments',
    status: 'active',
    owner: 'Ana Souza',
    last_deploy: '2026-08-16T14:22:00Z',
    created_at: '2025-03-12T10:00:00Z',
    endpoints_count: 24,
    releases_count: 18,
    environments_count: 3,
    members_count: 6,
  },
  {
    id: 2,
    name: 'App Delivery',
    description: 'Aplicativo de entregas com rastreamento em tempo real, carteira digital e gestão de pedidos.',
    framework: 'NestJS',
    language: 'TypeScript',
    repository: 'github.com/acme/delivery',
    status: 'active',
    owner: 'Bruno Lima',
    last_deploy: '2026-08-15T09:05:00Z',
    created_at: '2025-06-01T10:00:00Z',
    endpoints_count: 31,
    releases_count: 12,
    environments_count: 2,
    members_count: 9,
  },
  {
    id: 3,
    name: 'CRM Interno',
    description: 'Sistema de gestão de relacionamento com clientes, pipeline de vendas e automação de e-mails.',
    framework: 'Django',
    language: 'Python',
    repository: 'github.com/acme/crm',
    status: 'maintenance',
    owner: 'Carla Mendes',
    last_deploy: '2026-07-28T18:40:00Z',
    created_at: '2024-11-20T10:00:00Z',
    endpoints_count: 17,
    releases_count: 32,
    environments_count: 3,
    members_count: 4,
  },
  {
    id: 4,
    name: 'Biometria Facial',
    description: 'API de reconhecimento facial e verificação de identidade para onboarding digital.',
    framework: 'FastAPI',
    language: 'Python',
    repository: 'github.com/acme/biometry',
    status: 'planning',
    owner: 'Diego Rocha',
    last_deploy: '2026-06-10T11:30:00Z',
    created_at: '2026-05-15T10:00:00Z',
    endpoints_count: 8,
    releases_count: 2,
    environments_count: 1,
    members_count: 3,
  },
  {
    id: 5,
    name: 'Chat IA Suporte',
    description: 'Assistente virtual baseado em IA para atendimento ao cliente com respostas contextuais.',
    framework: 'Next.js',
    language: 'TypeScript',
    repository: 'github.com/acme/support-chat',
    status: 'active',
    owner: 'Eduarda Pires',
    last_deploy: '2026-08-17T07:55:00Z',
    created_at: '2026-01-08T10:00:00Z',
    endpoints_count: 14,
    releases_count: 9,
    environments_count: 2,
    members_count: 5,
  },
  {
    id: 6,
    name: 'Analytics SaaS',
    description: 'Plataforma de métricas e insights de produto com dashboards em tempo real.',
    framework: 'Rails',
    language: 'Ruby',
    repository: 'github.com/acme/analytics',
    status: 'archived',
    owner: 'Fábio Alves',
    last_deploy: '2026-02-14T20:10:00Z',
    created_at: '2024-05-03T10:00:00Z',
    endpoints_count: 0,
    releases_count: 44,
    environments_count: 2,
    members_count: 2,
  },
]

export const mockReleases: Release[] = [
  { id: 1, project_id: 1, version: '3.4.0', status: 'released', released_at: '2026-08-16T14:20:00Z', author: 'Ana Souza', changelog: ['Novo endpoint de split de pagamento', 'Melhorias no antifraude', 'Correção de timeout no checkout'] },
  { id: 2, project_id: 1, version: '3.3.1', status: 'released', released_at: '2026-07-22T10:00:00Z', author: 'Bruno Lima', changelog: ['Hotfix: falha na conciliação'] },
  { id: 3, project_id: 1, version: '3.4.1', status: 'in_progress', released_at: '2026-08-28T00:00:00Z', author: 'Ana Souza', changelog: ['Novo gateway PIX', 'Rate limiting por merchant'] },
  { id: 4, project_id: 1, version: '3.5.0', status: 'planned', released_at: '2026-09-15T00:00:00Z', author: 'Diego Rocha', changelog: ['Suporte a criptografia de cartões', 'Refatoração do webhook handler'] },
  { id: 5, project_id: 2, version: '2.1.0', status: 'released', released_at: '2026-08-15T09:00:00Z', author: 'Carla Mendes', changelog: ['Rastreamento em tempo real via WebSocket', 'Nova tela de status do pedido'] },
  { id: 6, project_id: 2, version: '2.0.5', status: 'released', released_at: '2026-07-30T15:00:00Z', author: 'Bruno Lima', changelog: ['Otimização de busca de restaurantes'] },
  { id: 7, project_id: 2, version: '2.2.0', status: 'in_progress', released_at: '2026-09-01T00:00:00Z', author: 'Eduarda Pires', changelog: ['Carteira digital v2', 'Programa de fidelidade'] },
  { id: 8, project_id: 3, version: '5.0.0', status: 'released', released_at: '2026-07-28T18:30:00Z', author: 'Fábio Alves', changelog: ['Pipeline de vendas visual', 'Automação de sequência de e-mails'] },
  { id: 9, project_id: 4, version: '0.9.0', status: 'planned', released_at: '2026-10-01T00:00:00Z', author: 'Diego Rocha', changelog: ['Protótipo de matching 1:N', 'Benchmark de latência'] },
  { id: 10, project_id: 5, version: '1.4.0', status: 'released', released_at: '2026-08-17T07:50:00Z', author: 'Eduarda Pires', changelog: ['Memória de contexto por cliente', 'Fallback para atendente humano'] },
]

export const mockEnvironments: Environment[] = [
  { id: 1, project_id: 1, name: 'Production', type: 'production', url: 'https://api.payments.acme.com', database: 'payments_prod', version: '3.4.0', status: 'active' },
  { id: 2, project_id: 1, name: 'Staging', type: 'staging', url: 'https://staging.api.payments.acme.com', database: 'payments_staging', version: '3.4.1', status: 'active' },
  { id: 3, project_id: 1, name: 'Development', type: 'development', url: 'http://localhost:3000', database: 'payments_dev', version: '3.4.1', status: 'inactive' },
  { id: 4, project_id: 2, name: 'Production', type: 'production', url: 'https://api.delivery.acme.com', database: 'delivery_prod', version: '2.1.0', status: 'active' },
  { id: 5, project_id: 2, name: 'Staging', type: 'staging', url: 'https://staging.api.delivery.acme.com', database: 'delivery_staging', version: '2.2.0', status: 'active' },
  { id: 6, project_id: 3, name: 'Production', type: 'production', url: 'https://crm.acme.com', database: 'crm_prod', version: '5.0.0', status: 'active' },
  { id: 7, project_id: 4, name: 'Production', type: 'production', url: 'https://biometry.acme.com', database: 'biometry_prod', version: '0.8.0', status: 'inactive' },
  { id: 8, project_id: 5, name: 'Production', type: 'production', url: 'https://chat.acme.com', database: 'chat_prod', version: '1.4.0', status: 'active' },
  { id: 9, project_id: 5, name: 'Development', type: 'development', url: 'http://localhost:3001', database: 'chat_dev', version: '1.5.0-beta', status: 'active' },
]

export const mockEndpoints: ApiEndpoint[] = [
  { id: 1, project_id: 1, environment_id: 1, method: 'GET', path: '/api/v1/transactions', description: 'Lista transações com paginação e filtros', response_time_ms: 142, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 2, project_id: 1, environment_id: 1, method: 'POST', path: '/api/v1/charges', description: 'Cria uma nova cobrança', response_time_ms: 385, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 3, project_id: 1, environment_id: 1, method: 'GET', path: '/api/v1/transactions/{id}', description: 'Detalhes de uma transação', response_time_ms: 118, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 4, project_id: 1, environment_id: 1, method: 'POST', path: '/api/v1/pix/qr', description: 'Gera QR Code PIX estático', response_time_ms: 210, status: 'degraded', last_checked_at: '2026-08-18T08:55:00Z' },
  { id: 5, project_id: 1, environment_id: 1, method: 'DELETE', path: '/api/v1/customers/{id}', description: 'Remove um cliente', response_time_ms: 0, status: 'down', last_checked_at: '2026-08-18T08:40:00Z' },
  { id: 6, project_id: 1, environment_id: 2, method: 'GET', path: '/api/v1/webhooks', description: 'Lista webhooks cadastrados', response_time_ms: 95, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 7, project_id: 2, environment_id: 4, method: 'GET', path: '/api/v2/orders', description: 'Lista pedidos do usuário', response_time_ms: 167, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 8, project_id: 2, environment_id: 4, method: 'POST', path: '/api/v2/orders', description: 'Cria novo pedido', response_time_ms: 322, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 9, project_id: 2, environment_id: 4, method: 'GET', path: '/api/v2/tracking/{order_id}', description: 'Rastreamento em tempo real', response_time_ms: 88, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 10, project_id: 2, environment_id: 4, method: 'POST', path: '/api/v2/wallet/transfer', description: 'Transferência entre carteiras', response_time_ms: 940, status: 'degraded', last_checked_at: '2026-08-18T08:50:00Z' },
  { id: 11, project_id: 3, environment_id: 6, method: 'GET', path: '/api/deals', description: 'Lista negócios do pipeline', response_time_ms: 203, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
  { id: 12, project_id: 5, environment_id: 8, method: 'POST', path: '/api/chat/sessions', description: 'Inicia uma nova sessão de chat', response_time_ms: 256, status: 'active', last_checked_at: '2026-08-18T09:00:00Z' },
]

export const mockTeamMembers: TeamMember[] = [
  { id: 1, project_id: 1, name: 'Ana Souza', email: 'ana@acme.com', role: 'owner', joined_at: '2025-03-12T10:00:00Z' },
  { id: 2, project_id: 1, name: 'Bruno Lima', email: 'bruno@acme.com', role: 'admin', joined_at: '2025-03-20T10:00:00Z' },
  { id: 3, project_id: 1, name: 'Carla Mendes', email: 'carla@acme.com', role: 'developer', joined_at: '2025-04-01T10:00:00Z' },
  { id: 4, project_id: 1, name: 'Diego Rocha', email: 'diego@acme.com', role: 'developer', joined_at: '2025-06-15T10:00:00Z' },
  { id: 5, project_id: 1, name: 'Eduarda Pires', email: 'eduarda@acme.com', role: 'viewer', joined_at: '2026-01-10T10:00:00Z' },
  { id: 6, project_id: 1, name: 'Fábio Alves', email: 'fabio@acme.com', role: 'viewer', joined_at: '2026-02-05T10:00:00Z' },
  { id: 7, project_id: 2, name: 'Bruno Lima', email: 'bruno@acme.com', role: 'owner', joined_at: '2025-06-01T10:00:00Z' },
  { id: 8, project_id: 5, name: 'Eduarda Pires', email: 'eduarda@acme.com', role: 'owner', joined_at: '2026-01-08T10:00:00Z' },
]

export const mockActivities: ActivityItem[] = [
  { id: 1, actor: 'Ana Souza', action: 'deployou', target: 'Portal de Pagamentos v3.4.0', timestamp: '2026-08-16T14:20:00Z' },
  { id: 2, actor: 'Eduarda Pires', action: 'deployou', target: 'Chat IA Suporte v1.4.0', timestamp: '2026-08-17T07:50:00Z' },
  { id: 3, actor: 'Bruno Lima', action: 'marcou o endpoint como degradado', target: 'POST /api/v2/wallet/transfer', timestamp: '2026-08-18T08:50:00Z' },
  { id: 4, actor: 'Carla Mendes', action: 'adicionou o membro', target: 'Diego Rocha no CRM Interno', timestamp: '2026-08-18T07:30:00Z' },
  { id: 5, actor: 'Fábio Alves', action: 'arquivou o projeto', target: 'Analytics SaaS', timestamp: '2026-08-17T20:15:00Z' },
  { id: 6, actor: 'Diego Rocha', action: 'criou a release planejada', target: 'Biometria Facial v0.9.0', timestamp: '2026-08-17T16:40:00Z' },
]

export const mockAlerts: AlertItem[] = [
  { id: 1, severity: 'critical', title: 'Endpoint fora do ar', detail: 'DELETE /api/v1/customers/{id} está retornando 500 há 20 minutos.', timestamp: '2026-08-18T08:40:00Z' },
  { id: 2, severity: 'warning', title: 'Latência acima do limite', detail: 'POST /api/v2/wallet/transfer ultrapassou 900ms (limite 500ms).', timestamp: '2026-08-18T08:50:00Z' },
  { id: 3, severity: 'info', title: 'Certificado SSL próximo da validade', detail: 'O certificado de api.delivery.acme.com expira em 12 dias.', timestamp: '2026-08-18T06:00:00Z' },
]

export const mockMetrics: DashboardMetrics = {
  totalProjects: mockProjects.length,
  apisOnline: mockEndpoints.filter((e) => e.status === 'active').length,
  activeReleases: mockReleases.filter((r) => r.status === 'released' || r.status === 'in_progress').length,
  teamMembers: new Set(mockTeamMembers.map((m) => m.email)).size,
  uptime: 99.96,
  deploySeries: [
    { name: 'Deploys', data: [3, 5, 2, 8, 6, 11, 7, 14, 9, 12, 8, 16] },
  ],
  apiSeries: [
    { name: 'Sucesso', data: [98, 99, 97, 99, 100, 99, 98, 99, 99, 100, 99, 99] },
    { name: 'Erros', data: [2, 1, 3, 1, 0, 1, 2, 1, 1, 0, 1, 1] },
  ],
  categories: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
}